
<h1 class="">About MAGE4</h1>
<p>
    <div><img src="https://drive.google.com/uc?id=1I1AhZt5egdv0ApJwHF67VP6N85fMovpG" /></div>
    We’re an innovative development agency building awesome websites, webshops and web applications with Latest Technologies. Check out our website <a target="_blank" href="http://mage4.com/">mage4.com</a>
</p>

<br/><hr/>
<h1 class="">Contact</h1>
<p>
    For Support, Inquiry, Contact or Quotation email us at: <a href="mailto:contact@mage4.com">contact@mage4.com</a> OR <a href="mailto:rehan@mage4.com">rehan@mage4.com</a>
</p>
